#!/usr/bin/env python2


prefix = """

/* Autogenerated Data */

#define DATA_LEN %

unsigned char data[%] = {
"""

suffix = """
};

"""


def chunk(l, n):
    return (l[i:i+n] for i in xrange(0, len(l), n))

def main(inf, outf, start=0, length=None):
    if start is not None:
        start = int(start)

    if length is not None:
        length = int(length)

    with open(inf, 'rb') as inf:
        with open(outf, 'w') as outf:
            data = inf.read()
            length = length if length is not None else len(data)

            if length is None:
                data = data[start:]
            else:
                data = data[start:start+length]

            output = ['%3d' % ord(d) for d in data]
            output = chunk(output, 15)
            output = ',\n'.join(4*' ' + o for o in (', '.join(o) for o in output))
            output = prefix.replace('%', repr(len(data))) + output + suffix

            outf.write(output)


if __name__ == "__main__":
    import sys
    main(*sys.argv[1:])

